blueprint:
  name: "Ring Intercom: Ring-to-Open (Gate-based, Emergency-aware)"
  description: >
    Gate-based Ring-to-Open automation with Arrival Window and configurable Emergency Mode.
    The door unlocks ONLY when the Ring-to-Open gate (input_boolean) is enabled.

  domain: automation

  input:
    ding_sensor:
      name: Ding (binary_sensor)
      selector:
        entity:
          domain: binary_sensor

    intercom_lock:
      name: Intercom lock
      selector:
        entity:
          domain: lock

    authorised_persons:
      name: Authorised persons (1..n)
      selector:
        entity:
          domain: person
          multiple: true

    ring_to_open_active:
      name: Ring-to-Open Active (input_boolean)
      description: Required helper acting as the single gatekeeper.
      selector:
        entity:
          domain: input_boolean

    arrival_active_minutes:
      name: Arrival active time (minutes)
      description: >
        How long Ring-to-Open stays enabled after a person arrives home.
        Only applies to the arrival scenario.
      default: 15
      selector:
        number:
          min: 1
          max: 180
          step: 1
          unit_of_measurement: min

    auto_reset_on_ding:
      name: Auto-reset after first successful Ding
      description: >
        If enabled, Ring-to-Open is turned OFF immediately
        after the door was unlocked via the Ding.
      default: false
      selector:
        boolean: {}

    enable_emergency_mode:
      name: Enable emergency mode
      default: false
      selector:
        boolean: {}

    emergency_battery_sensors:
      name: Emergency battery sensors (1..n)
      description: >
        Emergency mode triggers if ANY sensor is below the threshold.
      default: []
      selector:
        entity:
          domain: sensor
          multiple: true

    emergency_battery_threshold:
      name: Emergency battery threshold (%)
      default: 5
      selector:
        number:
          min: 1
          max: 50
          step: 1
          unit_of_measurement: "%"

    emergency_disable_conditions:
      name: Emergency mode – disable conditions
      description: Multiple selections allowed.
      default:
        - battery_ok
        - person_arrived
      selector:
        select:
          multiple: true
          options:
            - label: "All emergency batteries are OK again"
              value: battery_ok
            - label: "An authorised person arrives home"
              value: person_arrived
            - label: "Global emergency timeout expires"
              value: timeout

    emergency_timeout_minutes:
      name: Emergency timeout (minutes)
      description: Only used if timeout is selected above.
      default: 120
      selector:
        number:
          min: 5
          max: 1440
          step: 5
          unit_of_measurement: min

mode: restart

variables:
  ding_entity: !input ding_sensor
  lock_entity: !input intercom_lock
  persons: !input authorised_persons
  gate: !input ring_to_open_active

  emergency_enabled: !input enable_emergency_mode
  batt_entities: !input emergency_battery_sensors
  batt_threshold: !input emergency_battery_threshold
  disable_opts: !input emergency_disable_conditions

  batt_configured: "{{ batt_entities | length > 0 }}"

  any_person_home: >
    {{
      expand(persons)
      | selectattr('state','eq','home')
      | list
      | count > 0
    }}

  any_battery_low: >
    {{
      expand(batt_entities)
      | selectattr('state','not in',['unknown','unavailable','none'])
      | map(attribute='state')
      | map('float', 101)
      | select('lt', batt_threshold | float)
      | list
      | count > 0
    }}

  all_batteries_ok: >
    {{
      expand(batt_entities)
      | selectattr('state','not in',['unknown','unavailable','none'])
      | map(attribute='state')
      | map('float', 0)
      | select('ge', batt_threshold | float)
      | list
      | count == (expand(batt_entities) | count)
    }}

  disable_on_battery_ok: "{{ 'battery_ok' in disable_opts }}"
  disable_on_arrival: "{{ 'person_arrived' in disable_opts }}"
  disable_on_timeout: "{{ 'timeout' in disable_opts }}"

trigger:
  - id: ding_pressed
    platform: state
    entity_id: !input ding_sensor
    to: "on"

  - id: person_arrived
    platform: state
    entity_id: !input authorised_persons
    to: "home"

  - id: emergency_battery_low
    platform: template
    value_template: >
      {{ emergency_enabled and batt_configured and any_battery_low }}

  - id: emergency_battery_ok
    platform: template
    value_template: >
      {{ emergency_enabled and batt_configured and all_batteries_ok }}

action:
  - choose:

      # Arrival window
      - conditions:
          - condition: trigger
            id: person_arrived
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input ring_to_open_active
          - service: logbook.log
            data:
              name: Ring Intercom
              message: "Ring-to-Open ENABLED (Arrival window)"
          - delay:
              minutes: !input arrival_active_minutes
          - service: input_boolean.turn_off
            target:
              entity_id: !input ring_to_open_active
          - service: logbook.log
            data:
              name: Ring Intercom
              message: "Ring-to-Open DISABLED (Arrival timeout)"

      # Emergency enable
      - conditions:
          - condition: trigger
            id: emergency_battery_low
          - condition: template
            value_template: "{{ not any_person_home }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input ring_to_open_active
          - service: logbook.log
            data:
              name: Ring Intercom
              message: "Ring-to-Open ENABLED (Emergency mode)"

      # Emergency disable: battery ok
      - conditions:
          - condition: trigger
            id: emergency_battery_ok
          - condition: template
            value_template: "{{ disable_on_battery_ok }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input ring_to_open_active
          - service: logbook.log
            data:
              name: Ring Intercom
              message: "Ring-to-Open DISABLED (Emergency: batteries OK)"

      # Emergency disable: person arrived
      - conditions:
          - condition: trigger
            id: person_arrived
          - condition: template
            value_template: "{{ disable_on_arrival }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input ring_to_open_active
          - service: logbook.log
            data:
              name: Ring Intercom
              message: "Ring-to-Open DISABLED (Emergency: person arrived)"

      # Emergency disable: timeout
      - conditions:
          - condition: trigger
            id: emergency_battery_low
          - condition: template
            value_template: "{{ disable_on_timeout }}"
        sequence:
          - delay:
              minutes: !input emergency_timeout_minutes
          - service: input_boolean.turn_off
            target:
              entity_id: !input ring_to_open_active
          - service: logbook.log
            data:
              name: Ring Intercom
              message: "Ring-to-Open DISABLED (Emergency timeout)"

      # Unlock on Ding
      - conditions:
          - condition: trigger
            id: ding_pressed
          - condition: template
            value_template: "{{ any_person_home }}"
          - condition: state
            entity_id: !input ring_to_open_active
            state: "on"
        sequence:
          - service: lock.unlock
            target:
              entity_id: !input intercom_lock
          - service: logbook.log
            data:
              name: Ring Intercom
              message: "Door UNLOCKED (Ding + Ring-to-Open active)"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ auto_reset_on_ding }}"
                sequence:
                  - service: input_boolean.turn_off
                    target:
                      entity_id: !input ring_to_open_active
                  - service: logbook.log
                    data:
                      name: Ring Intercom
                      message: "Ring-to-Open DISABLED (Auto-reset)"

    default: []
